#!/home/software/opt/intel/oneapi/intelpython/python3.7/bin/python3.7

import os
from pathlib import Path
import argparse
from tempfile import mkstemp
from subprocess import run
import shlex
import h5py

def get_cfg():
    username = os.getlogin()
    parser = argparse.ArgumentParser(
        prog='make_tma',
        description='Make tag list',
    )
    parser.add_argument('start')
    parser.add_argument('end')
    parser.add_argument('-wd', '--work-dir', dest='workdirectory', required=False, default=Path(f'/work/{username}/'), type=lambda s: Path(s).absolute())
    parser.add_argument('-od', '--output-dir', dest='outputdirectory', required=False, default=Path.home(), type=lambda s: Path(s).absolute())
    parser.add_argument('-c', '--config', dest='configfile', required=True, type=lambda s: Path(s).absolute())
    parser.add_argument('-m', '--memlimit', dest='memorylimitgb', required=False, type=int, default=10)
    cfg = parser.parse_args()
    return cfg


def main(cfg):

    with h5py.File(cfg.configfile, 'r+') as h5f:
        h5f['common/log_directory'][...]=cfg.workdirectory.as_posix()
        h5f['common/csv/directory'][...]=cfg.workdirectory.as_posix()
        h5f['common/png/directory'][...]=cfg.workdirectory.as_posix()

    script = f"""#!/bin/bash

module load SACLA_tool/1.0.0

cd {cfg.workdirectory.as_posix()}
TimingMonitorAnalyzerCUI {cfg.configfile.as_posix()} {cfg.start} {cfg.end}
"""
    filename = Path(mkstemp(dir=cfg.workdirectory)[1])
    with open(filename, 'w') as fh:
        fh.write(script)
        fh.write(f'\nrm {filename.absolute().as_posix()}\n')

    ofile = cfg.outputdirectory / f'tma_{cfg.start}-{cfg.end}.o'
    efile = cfg.outputdirectory / f'tma_{cfg.start}-{cfg.end}.e'
    run(shlex.split(f'qsub -o {ofile.absolute().as_posix()} -e {efile.absolute().as_posix()} -l mem={cfg.memorylimitgb}gb {filename.absolute().as_posix()}'))


if __name__ == '__main__':
    cfg = get_cfg()
    main(cfg)
