#!/usr/bin/python3

import os
from subprocess import run
import shlex
import numpy as np
import matplotlib.pyplot as plt
import h5py

def get_cfg():
    username = os.getlogin()
    parser = argparse.ArgumentParser(
        prog='make_tma',
        description='Make tag list',
    )
    parser.add_argument('start')
    parser.add_argument('end')
    parser.add_argument('-b', '--background', dest='background', required=False, default=None)
    parser.add_argument('-wd', '--work-dir', dest='workdirectory', required=False, default=Path(f'/work/{username}/'), type=lambda s: Path(s).absolute())
    parser.add_argument('-od', '--output-dir', dest='outputdirectory', required=False, default=Path.home(), type=lambda s: Path(s).absolute())
    parser.add_argument('-c', '--config', dest='configfile', required=True, type=lambda s: Path(s).absolute())
    cfg = parser.parse_args()
    return cfg


def main(cfg):

    with h5py.File(cfg.configfile, 'r+') as h5f:
        h5f['common/log_directory'][...]=cfg.workdirectory
        h5f['common/csv/directory'][...]=cfg.workdirectory
        h5f['common/png/directory'][...]=cfg.workdirectory

    script = f"""#!/bin/bash

module load SACLA_tool/1.0.0
export LLST_PATH="/bl3strg/exp2018-2:/arcv1/recall/20231005/ExpData/bl3strg/exp2018-2"

cd {cfg.workdirectory.as_posix()}
TimingMonitorAnalyzerCUI {cfg.configfile.as_posix()} {cfg.start} {cfg.end}
"""
    filename = Path(mkstemp(dir=cfg.workdirectory)[1])
    with open(filename, 'w') as fh:
        fh.write(script)
        fh.write(f'\nrm {filename.absolute()}\n')

    ofile = cfg.outputdirectory / f'tma_{cfg.start}-{cfg.end}.o'
    efile = cfg.outputdirectory / f'tma_{cfg.start}-{cfg.end}.e'
    print(shlex.split(f'qsub {filename.absolute().as_posix()} -o {ofile.absolute().as_posix()} -e {efile.absolute().as_posix}'))
